PIKA_PARAMETERS = {
    'host': 'localhost',
}

UNICHECK_QUEUE_NAME = 'unicheck'
DOWNLOADER_QUEUE_NAME = 'download'

KV_POSTGRES = {
    'database': 'willbeams',
}

THUMBNAIL_RATIO = 4 / 3
THUMBNAIL_WIDTH = 400
THUMBNAIL_HEIGHT = round(THUMBNAIL_WIDTH / THUMBNAIL_RATIO)
